#pragma once
#include <wx/wx.h>

constexpr wxWindowID ID_COUNT_BASE = __COUNTER__;
constexpr wxWindowID ID_BTN_MOVE_TO_PREV_PAGE = wxID_HIGHEST + 1;
constexpr wxWindowID ID_BTN_MOVE_TO_NEXT_PAGE = ID_BTN_MOVE_TO_PREV_PAGE + 1;
constexpr wxWindowID ID_BTN_FIT_WIDTH = ID_BTN_MOVE_TO_NEXT_PAGE + 1;
constexpr wxWindowID ID_BTN_FIT_PAGE = ID_BTN_FIT_WIDTH + 1;
constexpr wxWindowID ID_BTN_ORIGINAL = ID_BTN_FIT_PAGE + 1;
constexpr wxWindowID ID_BTN_BOOKMARK_VIEW = ID_BTN_ORIGINAL + 1;
constexpr wxWindowID ID_BTN_ADD_MARK = ID_BTN_BOOKMARK_VIEW + 1;
constexpr wxWindowID ID_REMOVE_SELECTED_BOOKMARK = ID_BTN_ADD_MARK + 1;
constexpr wxWindowID ID_CLEAR_BOOKMARK = ID_REMOVE_SELECTED_BOOKMARK + 1;
constexpr wxWindowID ID_CLEAR_LATEST_READ_PAGE = ID_CLEAR_BOOKMARK + 1;
constexpr wxWindowID ID_MENU_RECENT_FILE_ITEM_BEGIN = wxID_HIGHEST + 1024;
constexpr wxWindowID ID_MENU_RECENT_FILE_ITEM_END = ID_MENU_RECENT_FILE_ITEM_BEGIN + 33;
